package iot.handler.sensor;

public enum SensorType {CO2, SOIL_TEMPERATURE, SOIL_HUMIDITY, BATTERY_VOLTAGE, LIGHT_INTENSITY, AIR_TEMPERATURE, AIR_HUMIDITY, 
						WIND_DIRECTION, REALTIME_WIND_SPEED, AVG_WIND_SPEED, HIGHEST_WIND_SPEED, RAINFALL_PER_HOUR, RAINFALL_PER_DAY, BEANSPROUT_DISTANCE}
